stages:
  - install_dependencies
  - install_app
  - pulumi_up

variables:
  npm_PATH: "/usr/share/npm:$npm_PATH"

before_script:
  - sudo apt-get update -qy
  - sudo apt-get install -y curl
  - sudo apt-get install -y unzip

install_dependencies:
  stage: install_dependencies
  script:
    - curl -fsSL https://get.pulumi.com | sh
    
  tags: 
    - test

install_app:
  stage: install_app
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install --update
    
  tags: 
    - test
  

# pulumi_up:
#   stage: pulumi_up
#   script:
#     - echo '#!/bin/bash' > pulumi-up.sh
#     - echo 'pulumi up --yes' >> pulumi-up.sh
#     - chmod +x pulumi-up.sh
#     - export PATH="/home/gitlab-runner/.pulumi/bin:$PATH"
#     - pulumi config set aws:accessKey $AWS_ACCESS_KEY_ID
#     - pulumi config set aws:secretKey $AWS_SECRET_ACCESS_KEY
#     - pulumi config set aws:region $AWS_DEFAULT_REGION
#     - pulumi login s3://$AWS_S3_BUCKET
#     - stackList=$(pulumi stack ls --json | tr -d '[:space:]')
#     - stackExists=$(echo "$stackList" | grep -q "$PULUMI_STACK" && echo true || echo false)

#     - if [ "$stackExists" == "false" ]; then pulumi stack init $PULUMI_STACK; else pulumi stack select $PULUMI_STACK; fi

#     - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
#     - sudo apt-get install -y nodejs
#     - sudo apt update
#     - npm install
#     - node -v
#     - npm -v
#     - npm install @pulumi/pulumi @pulumi/aws
#     - export PULUMI_CONFIG_PASSPHRASE="$PULUMI_CONFIG_PASSPHRASE"
#     - ./pulumi-up.sh

#   only:
#     - master

#   tags: 
#     - test


pulumi_up:
  stage: pulumi_up
  script:
    
    - echo '#!/bin/bash' > pulumi-up.sh
    - echo 'pulumi up --yes' >> pulumi-up.sh
    - chmod +x pulumi-up.sh
    - export PATH="/home/gitlab-runner/.pulumi/bin:$PATH"
    - pulumi login s3://$AWS_S3_BUCKET/$PULUMI_STACK
    - pulumi config set aws:accessKey $AWS_ACCESS_KEY_ID
    - pulumi config set aws:secretKey $AWS_SECRET_ACCESS_KEY

    - |
      stackList=$(pulumi stack ls --json | jq -r '.[].name');
      stackExists=$(echo "$stackList" | grep -q "$PULUMI_STACK" && echo "true" || echo "false");

      if [ "$stackExists" == "false" ]; then
        pulumi stack init ${PULUMI_STACK}
      else
        pulumi stack select ${PULUMI_STACK}
      fi

    - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - sudo apt update
    - npm install
    - node -v
    - npm -v
    - npm install @pulumi/pulumi @pulumi/aws
    - export PULUMI_CONFIG_PASSPHRASE="$PULUMI_CONFIG_PASSPHRASE"
    - ./pulumi-up.sh

  only:
    - master

  tags: 
    - test