
stages:
  - install_dependencies
  - install_app
  - pulumi_up

variables:
  npm_PATH: "/usr/share/npm:$npm_PATH"
  PULUMI_STACK: "ec2automation-s3-gitlab"

before_script:
  - sudo apt-get update -qy
  - sudo apt-get install -y curl
  - sudo apt-get install -y unzip
  - sudo apt-get install -y jq
  - sudo apt-get install -y dos2unix


install_dependencies:
  stage: install_dependencies
  script:
    - curl -fsSL https://get.pulumi.com | sh
    
  tags: 
    - test

install_app:
  stage: install_app
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install --update
    
  tags: 
    - test

pulumi_up:
  stage: pulumi_up
  script:
    
    - echo '#!/bin/bash' > pulumi-up.sh
    - echo 'pulumi up --yes' >> pulumi-up.sh
    - chmod +x pulumi-up.sh
    - export PATH="/home/gitlab-runner/.pulumi/bin:$PATH"
    
    - export PULUMI_CONFIG_PASSPHRASE="$PULUMI_CONFIG_PASSPHRASE"
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"

    - pulumi login s3://sandbox-pulumi-state-gitlab-01?region=us-east-1

    # - PULUMI_STACK_LIST=$(pulumi stack ls --json | tr -d '\n' | tr -d '[:space:]')
    #- stackList=$(pulumi stack ls --json | jq -r '.[].name')
    # - stackExists=$(echo "$PULUMI_STACK_LIST")
    - |
      set -e

      # Get the list of existing stacks
      stackList=$(pulumi stack ls --json | jq -r '.[].name')

      # Extract stack names using jq
      stackNames=$(echo "$stackList" | jq -r '.[].name')

      # Check if the desired stack exists
      if [[ "$stackNames" != "$PULUMI_STACK" ]]; then
        echo "Stack here is not exists. Initializing now..."
        pulumi stack init "$PULUMI_STACK"
      else
        echo "Stack here is exist. Selecting now ..."
        pulumi stack select "$PULUMI_STACK"
      fi

    - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - sudo apt update
    - npm install
    - node -v
    - npm -v
    - npm install @pulumi/pulumi @pulumi/aws
    - export PULUMI_CONFIG_PASSPHRASE="$PULUMI_CONFIG_PASSPHRASE"
    - ./pulumi-up.sh

  only:
    - master

  tags: 
    - test